#!/bin/bash
#update data from reprositories
sudo apt update
#install Apache + php + php-modules
sudo apt install apache2 php php-mysql libapache2-mod-php php-mbstring php-zip php-gd
#open 80/443 ports in firewall
sudo ufw app info "WWW Full"
#change Apache config
#install NGINX
sudo apt install nginx
#chenge NGINX config

#bigin wordpress script 
